### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by an0key** [kofec/domoticz-AirPurifier#3]
Not 100% sure if this should be raised here or against miio? 

./MyAir.py -h
Traceback (most recent call last):
  File "./MyAir.py", line 20, in <module>
    import miio.airpurifier
  File "/usr/local/lib/python3.4/dist-packages/miio/__init__.py", line 5, in <module>
    from miio.vacuum import Vacuum, VacuumException
  File "/usr/local/lib/python3.4/dist-packages/miio/vacuum.py", line 12, in <module>
    from .device import Device, DeviceException
  File "/usr/local/lib/python3.4/dist-packages/miio/device.py", line 331
    **extra_params}
     ^
SyntaxError: invalid syntax

pi@GLaDOS:~/domoticz/plugins/domoticz-AirPurifier $ python3 -V
Python 3.4.2
pi@GLaDOS:~/domoticz/plugins/domoticz-AirPurifier $ pip3 -V
pip 1.5.6 from /usr/lib/python3/dist-packages (python 3.4)
pi@GLaDOS:~/domoticz/plugins/domoticz-AirPurifier $ pip freeze
Pillow==2.6.1
PyBluez==0.18
PyYAML==3.12
RPi.GPIO==0.6.3
RTIMULib==7.2.1
appdirs==1.4.0
argcomplete==1.7.0
argparse==1.2.1
chardet==2.3.0
colorama==0.3.2
future==0.16.0
gpiozero==1.4.0
gyp==0.1
html5lib==0.999
lxkeymap==0.1
mcpi==0.1.1
ndg-httpsclient==0.3.2
numpy==1.8.2
picamera==1.13
pifacecommon==4.2.1
pifacedigitalio==3.1.0
pyOpenSSL==0.13.1
pyasn1==0.1.7
pybotvac==0.0.1
pygame==1.9.2a0
pygobject==3.14.0
pyserial==2.6
python-escpos==2.2.1.dev71-ng7860457
pyusb==1.0.0
qrcode==5.3
requests==2.4.3
scapy==2.2.0
sense-hat==2.2.0
six==1.8.0
spidev==3.0
urllib3==1.9.1
virtualenv==1.11.6
wheel==0.24.0
wsgiref==0.1.2

**Comment by kofec** [comment]
Please try the latest version

**Comment by kofec** [comment]
I have tested on latest stable version of openwrt and it is fine.
It is possible issue with many different version of openssl library. I highly recommend use openwrt as system on Raspberry pi or any other router which can be used as "home" for openwrt

**Comment by kofec** [comment]
I will closed if the problem still exist please reopen
