### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by smotx** [kofec/domoticz-AirPurifier#5]
Hi, 

On Rasp 3b+, in 'sudo' mode, with command :

`pip3 install -U python-miio`

i have this resutl :

` 

> arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/bui                                         ld/python3.5-6waWnr/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_                                         FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/in                                         clude/python3.5m -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.5/c/_cffi_backend.o
>   c/_cffi_backend.c:15:17: fatal error: ffi.h: Aucun fichier ou dossier de ce type
>    #include <ffi.h>
>                    ^
>   compilation terminated.
>   **error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1**
> 
>   ----------------------------------------
>   **Failed building wheel for cffi**
>   Running setup.py clean for cffi
> Failed to build cryptography cffi
> Installing collected packages: attrs, netifaces, appdirs, ifaddr, zeroconf, construct, asn1crypto, pycparser, c                                         ffi, cryptography, click, tqdm, pytz, python-miio
>   Running setup.py install for cffi ... error
> `

and 

` 

> creating build/temp.linux-armv7l-3.5/c
>     arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/b                                         uild/python3.5-6waWnr/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -                                         D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/                                         include/python3.5m -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.5/c/_cffi_backend.o
>     c/_cffi_backend.c:15:17: fatal error: ffi.h: Aucun fichier ou dossier de ce type
>      #include <ffi.h>
>                      ^
>     compilation terminated.
>     ****error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
> 
>     ----------------------------------------
> Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kijk7mg4/cffi/setup.py';f                                         =getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __f                                         ile__, 'exec'))" install --record /tmp/pip-6xe5vdte-record/install-record.txt --single-version-externally-manag                                         ed --compile" failed with error code 1 in /tmp/pip-build-kijk7mg4/cffi/****
> `
> 

and when i launch 
`pi@raspberrypi:~/domoticz/plugins/domoticz-AirPurifier $ ./MyAir.py 192.168.1.1 850000000000000000000000002 --debug
Traceback (most recent call last):
  File "./MyAir.py", line 11, in <module>
    import miio.airpurifier
ImportError: No module named 'miio'
`
Thx for help

**Comment by PNixx** [comment]
try `apt install libffi-dev`

**Comment by kofec** [comment]
I will closed if the problem still exist please reopen
