### ISSUE TITLE
Air Purifier 2S support

### ISSUE THREAD

**Issue by schurgan** [kofec/domoticz-AirPurifier#6]
Hello, is there ever support for Air Purifier 2S?  Actually, all except "Air Purifier - Source" switch, the 0-level does not work and errors occur in the log file.

Here is the excerpt from the log file:

2019-11-11 12:45:48.506 Error: (Air Purifier 2S) ----> Line 581 in '/home/pi/domoticz/plugins/domoticz-AirPurifier/plugin.py', function onCommand
2019-11-11 12:45:48.506 Error: (Air Purifier 2S) ----> Line 329 in '/home/pi/domoticz/plugins/domoticz-AirPurifier/plugin.py', function onCommand
2019-11-11 12:45:48.506 Error: (Air Purifier 2S) ----> Line 316 in '/usr/lib/python3.5/subprocess.py', function check_output
2019-11-11 12:45:48.506 Error: (Air Purifier 2S) ----> Line 398 in '/usr/lib/python3.5/subprocess.py', function run

Thank you for your work

**Comment by kofec** [comment]
Have you tried? ./MyAir.py 192.168.1.1 850000000000000000000000002 --debug

**Comment by schurgan** [comment]
I do not understand what to do ...

**Comment by schurgan** [comment]
I have 2 Purifiers.  An Air Purifier 2 and 2S.  At first everything works well.  Only the 2S I have the above problem.

**Comment by kofec** [comment]
On readme there is a description:
https://github.com/kofec/domoticz-AirPurifier/blob/master/README.md
First use script "MyAir.py" to verify if you have needed python modules e.g:

./MyAir.py 192.168.1.1 850000000000000000000000002 --debug
./MyAir.py -h
usage: MyAir.py [-h] [--mode {Auto,Favorite,Idle,Silent}]
                [--favoriteLevel {0,1,2,3,4,5,6,7,8,9,10}] [--power {ON,OFF}]
                [--debug]
                IPaddress token

Script which comunicate with AirPurfier 2.

positional arguments:
  IPaddress             IP address of AirPurfier
  token                 token to login to device

optional arguments:
  -h, --help            show this help message and exit
  --mode {Auto,Favorite,Idle,Silent}
                        choose mode operation
  --favoriteLevel {0,1,2,3,4,5,6,7,8,9,10}
                        choose mode operation
  --power {ON,OFF}      power ON/OFF
  --debug               if define more output is printed

**Comment by schurgan** [comment]
Last login: Mon Nov 11 21:06:19 2019 from 192.168.178.59
pi@raspberrypi:~$ cd domoticz/plugins/domoticz-AirPurifier
pi@raspberrypi:~/domoticz/plugins/domoticz-AirPurifier$ ./MyAir.py 192.168.178.30 cd8a75c2a727aca92bd761c6db70e5be --debug
Namespace(IPaddress='192.168.178.30', debug=True, favoriteLevel=None, mode=None, power=None, token='cd8a75c2a727aca92bd761c6db70e5be')
<AirPurifierStatus power=off, aqi=5, average_aqi=4, temperature=21.3, humidity=61%, mode=OperationMode.Auto, led=True, led_brightness=None, illuminance=52, buzzer=False, child_lock=False, favorite_level=1, filter_life_remaining=99, filter_hours_used=13, use_time=None, purify_volume=None, motor_speed=0, motor2_speed=None, volume=None, filter_rfid_product_id=0:0:30:33, filter_rfid_tag=80:5f:68:7a:4e:d9:4, filter_type=FilterType.Regular, learn_mode=False, sleep_mode=None, sleep_time=None, sleep_mode_learn_count=None, extra_features=0, turbo_mode_supported=False, auto_detect=None, button_pressed=power>
pi@raspberrypi:~/domoticz/plugins/domoticz-AirPurifier$

**Comment by schurgan** [comment]
Last login: Mon Nov 11 21:06:19 2019 from 192.168.178.59
pi@raspberrypi:~$ cd domoticz/plugins/domoticz-AirPurifier
pi@raspberrypi:~/domoticz/plugins/domoticz-AirPurifier$ ./MyAir.py 192.168.178.30 cd8a75c2a727aca92bd761c6db70e5be --debug
Namespace(IPaddress='192.168.178.30', debug=True, favoriteLevel=None, mode=None, power=None, token='cd8a75c2a727aca92bd761c6db70e5be')
<AirPurifierStatus power=off, aqi=5, average_aqi=4, temperature=21.3, humidity=61%, mode=OperationMode.Auto, led=True, led_brightness=None, illuminance=52, buzzer=False, child_lock=False, favorite_level=1, filter_life_remaining=99, filter_hours_used=13, use_time=None, purify_volume=None, motor_speed=0, motor2_speed=None, volume=None, filter_rfid_product_id=0:0:30:33, filter_rfid_tag=80:5f:68:7a:4e:d9:4, filter_type=FilterType.Regular, learn_mode=False, sleep_mode=None, sleep_time=None, sleep_mode_learn_count=None, extra_features=0, turbo_mode_supported=False, auto_detect=None, button_pressed=power>
pi@raspberrypi:~/domoticz/plugins/domoticz-AirPurifier$

**Comment by schurgan** [comment]
Last login: Mon Nov 11 21:06:19 2019 from 192.168.178.59
pi@raspberrypi:~$ cd domoticz/plugins/domoticz-AirPurifier
pi@raspberrypi:~/domoticz/plugins/domoticz-AirPurifier$ ./MyAir.py 192.168.178.30 xxxxxxxxxxxxxxxxxxxxxxxx --debug
Namespace(IPaddress='192.168.178.30', debug=True, favoriteLevel=None, mode=None, power=None, token='xxxxxxxxxxxxxxxxxxxxxx')
<AirPurifierStatus power=off, aqi=5, average_aqi=4, temperature=21.3, humidity=61%, mode=OperationMode.Auto, led=True, led_brightness=None, illuminance=52, buzzer=False, child_lock=False, favorite_level=1, filter_life_remaining=99, filter_hours_used=13, use_time=None, purify_volume=None, motor_speed=0, motor2_speed=None, volume=None, filter_rfid_product_id=0:0:30:33, filter_rfid_tag=80:5f:68:7a:4e:d9:4, filter_type=FilterType.Regular, learn_mode=False, sleep_mode=None, sleep_time=None, sleep_mode_learn_count=None, extra_features=0, turbo_mode_supported=False, auto_detect=None, button_pressed=power>
pi@raspberrypi:~/domoticz/plugins/domoticz-AirPurifier$

**Comment by schurgan** [comment]
`Last login: Mon Nov 11 21:06:19 2019 from 192.168.178.59
pi@raspberrypi:~$ cd domoticz/plugins/domoticz-AirPurifier
pi@raspberrypi:~/domoticz/plugins/domoticz-AirPurifier$ ./MyAir.py 192.168.178.30 cd8a75c2a727aca92bd761c6db70e5be --debug
Namespace(IPaddress='192.168.178.30', debug=True, favoriteLevel=None, mode=None, power=None, token='cd8a75c2a727aca92bd761c6db70e5be')
<AirPurifierStatus power=off, aqi=5, average_aqi=4, temperature=21.3, humidity=61%, mode=OperationMode.Auto, led=True, led_brightness=None, illuminance=52, buzzer=False, child_lock=False, favorite_level=1, filter_life_remaining=99, filter_hours_used=13, use_time=None, purify_volume=None, motor_speed=0, motor2_speed=None, volume=None, filter_rfid_product_id=0:0:30:33, filter_rfid_tag=80:5f:68:7a:4e:d9:4, filter_type=FilterType.Regular, learn_mode=False, sleep_mode=None, sleep_time=None, sleep_mode_learn_count=None, extra_features=0, turbo_mode_supported=False, auto_detect=None, button_pressed=power>
pi@raspberrypi:~/domoticz/plugins/domoticz-AirPurifier$`

**Comment by kofec** [comment]
As I understand it read values OK but when you want to change state/mode it didn't work right ?
Can you try:
./MyAir.py 192.168.178.30 cd8a75c2a727aca92bd761c6db70e5be --mode Auto

**Comment by schurgan** [comment]
Apparently Idle is like Auto
On the picture you can see the difference between Air Purifier 2 and 2S
![](https://i.imgur.com/bsMJ54l.jpg)

**Comment by schurgan** [comment]
At 2S there is no Level "Auto"

**Comment by kofec** [comment]
Base on logs provided by you:
`humidity=61%, mode=OperationMode.Auto, led=True`

**Comment by schurgan** [comment]
Yes, I saw that, but you see, you can not keep that one.  If you turn it off automatically must go to "Auto", but he does not.

**Comment by schurgan** [comment]
This is debug of Air Purifier 2:
```
Last login: Mon Nov 11 21:46:14 2019 from 192.168.178.59
pi@raspberrypi:~$ cd domoticz/plugins/domoticz-AirPurifier                   pi@raspberrypi:~/domoticz/plugins/domoticz-AirPurifier$ ./MyAir.py 192.168.178.29 42132847982c8cdf421d3d01724d5e53 --debug
Namespace(IPaddress='192.168.178.29', debug=True, favoriteLevel=None, mode=None, power=None, token='42132847982c8cdf421d3d01724d5e53')
<AirPurifierStatus power=off, aqi=10, average_aqi=8, temperature=20.2, humidity=61%, mode=OperationMode.Idle, led=True, led_brightness=LedBrightness.Dim, illuminance=None, buzzer=False, child_lock=False, favorite_level=16, filter_life_remaining=74, filter_hours_used=878, use_time=3077700, purify_volume=39448, motor_speed=0, motor2_speed=None, volume=None, filter_rfid_product_id=None, filter_rfid_tag=None, filter_type=None, learn_mode=True, sleep_mode=SleepMode.Idle, sleep_time=84764, sleep_mode_learn_count=30, extra_features=1, turbo_mode_supported=True, auto_detect=None, button_pressed=None>
pi@raspberrypi:~/domoticz/plugins/domoticz-AirPurifier$
```

**Comment by schurgan** [comment]
On the picture is "Auto"

**Comment by kofec** [comment]
Can you "disable" Air Purifier 2 in "Hardware" tab in Domoticz and check if the problem still exist.

**Comment by schurgan** [comment]
Yes, it is still the same

**Comment by kofec** [comment]
Can you change the flag "Debug" to True and paste a little bit more logs from domoticz.

**Comment by kofec** [comment]
One more thing. Which version of python-miio do you have ? 
https://github.com/rytilahti/python-miio/commit/54befeff6cf20c08a5e064744d114e1f518ac52a

**Comment by schurgan** [comment]
Should be the last.  I have installed after your instructions

**Comment by kofec** [comment]
Can you "git pull" the repository. I have add some more debug and try/exceptions.

**Comment by schurgan** [comment]
2019-11-13 05:03:00.369 (Air Purifier 2S) onCommand called for Unit 10: Parameter 'Off', Level: 0

2019-11-13 05:03:05.132 (Air Purifier 2S) Starting device update

2019-11-13 05:03:05.132 (Air Purifier 2S) Update unit=1; nValue=0; sValue=5

2019-11-13 05:03:05.148 (Air Purifier 2S) Update unit=2; nValue=1; sValue=Great air quality

2019-11-13 05:03:05.159 (Air Purifier 2S) Update unit=3; nValue=0; sValue=21.1

2019-11-13 05:03:05.170 (Air Purifier 2S) Update unit=4; nValue=61; sValue=1

2019-11-13 05:03:05.181 (Air Purifier 2S) Update unit=5; nValue=0; sValue=0

2019-11-13 05:03:05.193 (Air Purifier 2S) Update unit=6; nValue=0; sValue=4

**Comment by schurgan** [comment]
And I have that with Air Purifier 2. Here something more happens
2019-11-13 05:09:14.512 (Air Purifier 2) Update 0:'AirPurifier OFF' (Air Purifier 2 - Power)

2019-11-13 05:09:14.546 (Air Purifier 2) Update 0:'0' (Air Purifier 2 - Source)

2019-11-13 05:09:14.546 (Air Purifier 2) Starting device update

2019-11-13 05:09:14.546 (Air Purifier 2) Update unit=1; nValue=0; sValue=9

2019-11-13 05:09:14.559 (Air Purifier 2) Update unit=2; nValue=1; sValue=Great air quality

2019-11-13 05:09:14.578 (Air Purifier 2) Update unit=3; nValue=0; sValue=19.9

2019-11-13 05:09:14.589 (Air Purifier 2) Update unit=4; nValue=61; sValue=1

2019-11-13 05:09:14.607 (Air Purifier 2) Update unit=5; nValue=0; sValue=0

2019-11-13 05:09:14.618 (Air Purifier 2) Update unit=6; nValue=0; sValue=8

2019-11-13 05:09:14.627 (Air Purifier 2) onCommand called for Unit 10: Parameter 'Off', Level: 0

**Comment by schurgan** [comment]
Air Purifier 2S - Source is not activated

**Comment by schurgan** [comment]
And I have that with Air Purifier 2. Here something more happens

2019-11-13 05:18:01.802 (Air Purifier 2) Starting device update

2019-11-13 05:18:01.802 (Air Purifier 2) Update unit=1; nValue=0; sValue=10

2019-11-13 05:18:01.816 (Air Purifier 2) Update unit=2; nValue=1; sValue=Great air quality

2019-11-13 05:18:01.827 (Air Purifier 2) Update unit=3; nValue=0; sValue=19.9

2019-11-13 05:18:01.836 (Air Purifier 2) Update unit=4; nValue=60; sValue=0

2019-11-13 05:18:01.845 (Air Purifier 2) Update unit=5; nValue=0; sValue=0

2019-11-13 05:18:01.855 (Air Purifier 2) Update unit=6; nValue=0; sValue=8

2019-11-13 05:18:01.866 (Air Purifier 2) onCommand called for Unit 10: Parameter 'Off', Level: 0

**Comment by kofec** [comment]
There is something with reported power state. Can you try.
./MyAir.py 192.168.178.30 cd8a75c2a727aca92bd761c6db70e5be --power ON --debug
./MyAir.py 192.168.178.30 cd8a75c2a727aca92bd761c6db70e5be --mode Auto --debug
./MyAir.py 192.168.178.30 cd8a75c2a727aca92bd761c6db70e5be --debug

**Comment by schurgan** [comment]
`Last login: Wed Nov 13 18:31:09 2019 from 192.168.178.59
pi@raspberrypi:~$ cd domoticz/plugins/domoticz-AirPurifier
pi@raspberrypi:~/domoticz/plugins/domoticz-AirPurifier$ ./MyAir.py 192.168.178.30 cd8a75c2a727aca92bd761c6db70e5be --power ON --debug
Namespace(IPaddress='192.168.178.30', debug=True, favoriteLevel=None, mode=None, power='ON', token='cd8a75c2a727aca92bd761c6db70e5be')
<AirPurifierStatus power=off, aqi=5, average_aqi=4, temperature=21.5, humidity=61%, mode=OperationMode.Auto, led=True, led_brightness=None, illuminance=19, buzzer=False, child_lock=False, favorite_level=1, filter_life_remaining=99, filter_hours_used=14, use_time=None, purify_volume=None, motor_speed=0, motor2_speed=None, volume=None, filter_rfid_product_id=0:0:30:33, filter_rfid_tag=80:5f:68:7a:4e:d9:4, filter_type=FilterType.Regular, learn_mode=False, sleep_mode=None, sleep_time=None, sleep_mode_learn_count=None, extra_features=0, turbo_mode_supported=False, auto_detect=None, button_pressed=power>
pi@raspberrypi:~/domoticz/plugins/domoticz-AirPurifier$ ./MyAir.py 192.168.178.30 cd8a75c2a727aca92bd761c6db70e5be --mode Auto --debug
Namespace(IPaddress='192.168.178.30', debug=True, favoriteLevel=None, mode='Auto', power=None, token='cd8a75c2a727aca92bd761c6db70e5be')
<AirPurifierStatus power=on, aqi=5, average_aqi=4, temperature=21.5, humidity=61%, mode=OperationMode.Auto, led=True, led_brightness=None, illuminance=54, buzzer=False, child_lock=False, favorite_level=1, filter_life_remaining=99, filter_hours_used=14, use_time=None, purify_volume=None, motor_speed=0, motor2_speed=None, volume=None, filter_rfid_product_id=0:0:30:33, filter_rfid_tag=80:5f:68:7a:4e:d9:4, filter_type=FilterType.Regular, learn_mode=False, sleep_mode=None, sleep_time=None, sleep_mode_learn_count=None, extra_features=0, turbo_mode_supported=False, auto_detect=None, button_pressed=power>
pi@raspberrypi:~/domoticz/plugins/domoticz-AirPurifier$ ./MyAir.py 192.168.178.30 cd8a75c2a727aca92bd761c6db70e5be --debug
Namespace(IPaddress='192.168.178.30', debug=True, favoriteLevel=None, mode=None, power=None, token='cd8a75c2a727aca92bd761c6db70e5be')
<AirPurifierStatus power=on, aqi=5, average_aqi=4, temperature=21.5, humidity=61%, mode=OperationMode.Auto, led=True, led_brightness=None, illuminance=54, buzzer=False, child_lock=False, favorite_level=1, filter_life_remaining=99, filter_hours_used=14, use_time=None, purify_volume=None, motor_speed=0, motor2_speed=None, volume=None, filter_rfid_product_id=0:0:30:33, filter_rfid_tag=80:5f:68:7a:4e:d9:4, filter_type=FilterType.Regular, learn_mode=False, sleep_mode=None, sleep_time=None, sleep_mode_learn_count=None, extra_features=0, turbo_mode_supported=False, auto_detect=None, button_pressed=power>`

**Comment by schurgan** [comment]
> Last login: Wed Nov 13 18:31:09 2019 from 192.168.178.59
pi@raspberrypi:~$ cd domoticz/plugins/domoticz-AirPurifier
pi@raspberrypi:~/domoticz/plugins/domoticz-AirPurifier$ ./MyAir.py 192.168.178.30 cd8a75c2a727aca92bd761c6db70e5be --power ON --debug
Namespace(IPaddress='192.168.178.30', debug=True, favoriteLevel=None, mode=None, power='ON', token='cd8a75c2a727aca92bd761c6db70e5be')
<AirPurifierStatus power=off, aqi=5, average_aqi=4, temperature=21.5, humidity=61%, mode=OperationMode.Auto, led=True, led_brightness=None, illuminance=19, buzzer=False, child_lock=False, favorite_level=1, filter_life_remaining=99, filter_hours_used=14, use_time=None, purify_volume=None, motor_speed=0, motor2_speed=None, volume=None, filter_rfid_product_id=0:0:30:33, filter_rfid_tag=80:5f:68:7a:4e:d9:4, filter_type=FilterType.Regular, learn_mode=False, sleep_mode=None, sleep_time=None, sleep_mode_learn_count=None, extra_features=0, turbo_mode_supported=False, auto_detect=None, button_pressed=power>
pi@raspberrypi:~/domoticz/plugins/domoticz-AirPurifier$ ./MyAir.py 192.168.178.30 cd8a75c2a727aca92bd761c6db70e5be --mode Auto --debug
Namespace(IPaddress='192.168.178.30', debug=True, favoriteLevel=None, mode='Auto', power=None, token='cd8a75c2a727aca92bd761c6db70e5be')
<AirPurifierStatus power=on, aqi=5, average_aqi=4, temperature=21.5, humidity=61%, mode=OperationMode.Auto, led=True, led_brightness=None, illuminance=54, buzzer=False, child_lock=False, favorite_level=1, filter_life_remaining=99, filter_hours_used=14, use_time=None, purify_volume=None, motor_speed=0, motor2_speed=None, volume=None, filter_rfid_product_id=0:0:30:33, filter_rfid_tag=80:5f:68:7a:4e:d9:4, filter_type=FilterType.Regular, learn_mode=False, sleep_mode=None, sleep_time=None, sleep_mode_learn_count=None, extra_features=0, turbo_mode_supported=False, auto_detect=None, button_pressed=power>
pi@raspberrypi:~/domoticz/plugins/domoticz-AirPurifier$ ./MyAir.py 192.168.178.30 cd8a75c2a727aca92bd761c6db70e5be --debug
Namespace(IPaddress='192.168.178.30', debug=True, favoriteLevel=None, mode=None, power=None, token='cd8a75c2a727aca92bd761c6db70e5be')
<AirPurifierStatus power=on, aqi=5, average_aqi=4, temperature=21.5, humidity=61%, mode=OperationMode.Auto, led=True, led_brightness=None, illuminance=54, buzzer=False, child_lock=False, favorite_level=1, filter_life_remaining=99, filter_hours_used=14, use_time=None, purify_volume=None, motor_speed=0, motor2_speed=None, volume=None, filter_rfid_product_id=0:0:30:33, filter_rfid_tag=80:5f:68:7a:4e:d9:4, filter_type=FilterType.Regular, learn_mode=False, sleep_mode=None, sleep_time=None, sleep_mode_learn_count=None, extra_features=0, turbo_mode_supported=False, auto_detect=None, button_pressed=power>
pi@raspberrypi:~/domoticz/plugins/domoticz-AirPurifier$

**Comment by kofec** [comment]
It looks like there is an issue when call "off".
Can you change the flag "Debug" to True and paste a little bit more logs from Domoticz.
And also try
./MyAir.py 192.168.178.30 cd8a75c2a727aca92bd761c6db70e5be --power=OFF
./MyAir.py 192.168.178.30 cd8a75c2a727aca92bd761c6db70e5be --power=ON

**Comment by schurgan** [comment]
With on and off there is no problem.  The level "Auto" does not exist or it can not be made from "Auto"

**Comment by kofec** [comment]
I will closed if the problem still exist please reopen
